### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by alissamune** [MarkEdmondson1234/gtmR#2]
Hi!

I'm trying to authenticate using gtm_auth() but I get this error every time:

`Error in googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  : 
  Cannot authenticate - options(googleAuthR.scopes.selected) needs to be set to includehttps://www.googleapis.com/auth/tagmanager.readonly or https://www.googleapis.com/auth/tagmanager.edit.containers
In addition: Warning message:
In googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :
  travis_environment_var argument is now unsupported and does nothing`

Is there anything I can do to solve it?

**Comment by MarkEdmondson1234** [comment]
I suggest using https://github.com/IronistM/googleTagManageR instead, as thats way more maintained and with more documentation and features. 

The specific error is one where the scopes have not been set for authentication, which can be done via `gar_set_client()` but see the website `googleAuthR` for details on that, but you should only need that if you want to build your own API library, if you just need to use the API go for the library mentioned above thats dealt with these details already.

**Comment by alissamune** [comment]
Thank you very much :)
